<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header bg-red">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Warning!</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="id" name="id" />
                <p class="content-warning"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-close" data-dismiss="modal">Close</button>
                <a class="btn btn-primary delete-all">Yes</a>
            </div>
        </div>
    </div>
</div>
<!-- footer content -->
<div id="loading" hidden style="position: fixed;z-index: 10000;top: 0px;left: 0px;width: 100%;height: 100%;background: #fff;filter: alpha(opacity=85);opacity: 1;background: rgba(255, 255,255,0);text-align: center; color:#f00;">
    <div style="background-color: #FDF7CC;border: 1px solid #FDC86C;border-radius: 4px;padding: 1px;margin: 20px auto;width: 50%;">
        <img src="<?php echo $this->url->getStatic('backend/img/waiting.gif'); ?>"
             alt='Processing'
             title='Processing'
             style="vertical-align:middle;position: relative;z-index: 10001;"/>Processing <span id="percent">0%</span>. Please waiting for the system to run!
    </div>
</div>
<footer>
    <div class="pull-right">
        Copyright ©1997 - <?php echo date("Y",time()) ;?> 123tyso
    </div>
    <div class="clearfix"></div>
</footer>
<!-- /footer content -->
</div>
</div>

<script src="<?php echo $this->url->getStatic('backend/'); ?>js/select2/select2.min.js"></script>
<!-- Bootstrap -->
<script src="<?php echo $this->url->getStatic('shared/js/');?>bootstrap.min.js"></script>
<!--Datetime-->
<script type="text/javascript" src="<?php echo $this->url->getStatic("/backend/js/datepicker.js"); ?>"></script>
<!-- Custom Theme Scripts -->
<script src="<?php echo $this->url->getStatic('backend/js/');?>custom.min.js"></script>
<script src="<?php echo $this->url->getStatic('backend/js/');?>utils.js?v=<?php echo time(); ?>"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/ls.unveilhooks.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/lazysizes.min.js"></script>
<script src="<?php echo $this->url->getStatic('backend/ckeditor/'); ?>ckeditor.js"></script>
<script>
    $(".select").select2();
</script>

</body>
</html>