<script>
    $( document ).ready(function() {
        $('form[name=banner-form]').submit(function(event) {
            var valid = true;
            if($( "select#slcController option:checked" ).val()==0) {
                $('.msg-controller').text('Controller is required.');
                $('#slcController').addClass("border-red");
                valid = false;
            } else {
                $('.msg-controller').text('');
                $('#slcController').removeClass("border-red");
            }
            if($('input[name=txtImage]').val() == '') {
                $('.msg-img').text('Image field is required.');
                $('#txtImage').addClass("border-red");
                valid = false;
            } else {
                $('.msg-img').text('');
                $('#txtImage').removeClass("border-red");
            }
            if($('input[name=txtImageMobile]').val() == '') {
                $('.msg-img-mobile').text('Image Mobile field is required.');
                $('#txtImageMobile').addClass("border-red");
                valid = false;
            } else {
                $('.msg-img-mobile').text('');
                $('#txtImageMobile').removeClass("border-red");
            }
            if($('input[name=txtTitle]').val() == '') {
                $('.msg-title').text('Title field is required.');
                $('#txtTitle').addClass("border-red");
                valid = false;
            } else {
                $('.msg-title').text('');
                $('#txtTitle').removeClass("border-red");
            }
            if($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }
            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=sbmBanner]').prop('disabled', true);
            }
        });

    });
</script>

<div class="page-title">
    <div class="title_left">
        <h3 class="banner-title">Banner </h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Create</div>
            <div class="x_content">
                <br />
                <form name="banner-form" id="banner-form" action="<?php echo $this->url->get('/banner/create'); ?>" data-parsley-validate class="form-horizontal form-label-left" method="post">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Controller <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select id="slcController" name="slcController" class="form-control col-md-7 col-xs-12  <?php echo (isset($messages["controller"])) ? $messages["status"] : ""; ?>" >
                                <option value="">Select Controller...</option>
                                <?php echo isset($select_controller)? $select_controller : ''?>
                            </select>
                            <span class="text-danger msg-controller"><?php echo isset($messages["controller"]) ? $messages["controller"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Image <span class="text-danger">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["banner_image"]) ? $formData["banner_image"] : "" ?>" type="text" id="txtImage" name="txtImage"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["image"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-img"><?php echo isset($messages["image"]) ? $messages["image"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Image Mobile <span class="text-danger">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["banner_image_mobile"]) ? $formData["banner_image_mobile"] : "" ?>" type="text" id="txtImageMobile" name="txtImageMobile" class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["image_mobile"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-img-mobile"><?php echo isset($messages["image_mobile"]) ? $messages["image_mobile"] : "";?></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Title  <span class="text-danger">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["banner_title"]) ? $formData["banner_title"] : "" ?>" type="text" id="txtTitle" name="txtTitle"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["title"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-title"><?php echo isset($messages["title"]) ? $messages["title"] : ""; ?></span>
                        </div>
                    </div>


                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Subtitle </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea class="form-control" id="txtSubtitle" name ="txtSubtitle" style="height: 112px;" ><?php echo isset($formData["banner_subtitle"]) ? $formData["banner_subtitle"] : "" ?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Content </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea class="form-control" id="txtContent" name ="txtContent" style="height: 112px;" ><?php echo isset($formData["banner_content"]) ? $formData["banner_content"] : "" ?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Link</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["banner_link"]) ? $formData["banner_link"] : "" ?>" type="text" id="txtLink" name="txtLink"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["link"])  ) ? $messages["status"] : ""; ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Start time </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php
                            $banner_start_time = "";
                            if (isset($formData["banner_start_time"])){
                                $banner_start_time = $formData["banner_start_time"];
                            }
                            if ($banner_start_time != 0 || !empty($banner_start_time)){
                                $banner_start_time = date('m/d/Y H:i', $this->my->localTime($banner_start_time));
                            } else {
                                $banner_start_time = "";
                            }
                            ?>
                            <input value="<?php echo $banner_start_time ?>" type="text" id="txtStartTime"
                                   data-timepicker="true"  placeholder="MM/DD/YYYY hh:MM" data-time-format='hh:ii' name="txtStartTime"
                                   class="form-control col-md-7 col-xs-12 datepicker-here <?php echo isset($messages["banner_start_time"]) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-start-time"><?php echo isset($messages["banner_start_time"]) ? $messages["banner_start_time"] : ""; ?></span>

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">End time  </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php
                            $banner_end_time = "";
                            if (isset($formData["banner_end_time"])) {
                                $banner_end_time = $formData["banner_end_time"];
                            }
                            if ($banner_end_time != 0 || !empty($banner_end_time)) {
                                $banner_end_time = date('m/d/Y H:i', $this->my->localTime($banner_end_time));
                            } else {
                                $banner_end_time = "";
                            }
                            ?>
                            <input value="<?php echo $banner_end_time?>" type="text"  placeholder="MM/DD/YYYY hh:MM"
                                   id="txtEndTime" data-timepicker="true" data-time-format='hh:ii' name="txtEndTime"
                                   class="form-control col-md-7 col-xs-12 datepicker-here <?php echo isset($messages["banner_end_time"]) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-end-time"><?php echo isset($messages["banner_end_time"]) ? $messages["banner_end_time"] : ""; ?></span>

                        </div>

                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Order <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="10" value="<?php echo isset($formData["banner_order"]) ? $formData["banner_order"] : "" ?>" type="text" id="txtOrder" name="txtOrder"  class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["order"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-order"><?php echo isset($messages["order"]) ? $messages["order"] : "";?></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Active </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive" value="Y" <?php echo (isset($formData["banner_active"]) && $formData["banner_active"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive" value="N" <?php echo (isset($formData["banner_active"]) && $formData["banner_active"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Locations</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 ">
                            <div class="toggles ">
                                <div class="toggle-item">
                                    <div class="toggle-heading  ">
                                        <h4>Show/Hide</h4>
                                    </div>
                                    <div class="toggle-content" hidden >
                                        <?php foreach ($list_banner_locations as $item) { ?>
                                            <div class="col-md-3 country_block">
                                                <label class="container_checkbox" >
                                                    <?php echo $item['country_name'] ?>
                                                    <input <?php echo $list_banner_locations_selected != NULL && in_array($item['country_code'], $list_banner_locations_selected) ? 'checked' : ''; ?>
                                                            type="checkbox" class="form-control check "
                                                            name="dataBannerLocations[]"
                                                            id="<?php echo $item['country_code'] ?>"
                                                            value="<?php echo $item['country_code'] ?>">
                                                    <span class="checkmark_checkbox"></span>
                                                </label>
                                            </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmBanner" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="/banner">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
